services:
  - type: web
    name: standup-bot
    env: python
    repo: https://github.com/rosenmarkov35/ServeStandUp-Bot
    plan: free
    branch: main
    buildCommand: ""
    startCommand: python bot.py
    autoDeploy: true
    envVars:
      - key: DISCORD_TOKEN
        sync: false
